language: node_js
node_js:
  - "node"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install --save-dev gulp-cli bower
  - npm install
  - bower install
script:
  - gulp default
  - gulp nuget-pack --apikey $apikey
  
